print('checks if all the characters of a string are alphanumeric (a-z, A-Z and 0-9)')
print ('ab1234'.isalnum())
print ('ab123#'.isalnum())
print("-"*50)
print('checks if all the characters of a string are alphabetical (a-z and A-Z).')
print ('abcD'.isalpha())
print ('abcd1'.isalpha())
print("-"*50)
print('checks if all the characters of a string are digits (0-9).')
print ('1234'.isdigit())
print ('123edsd'.isdigit())
print("-"*50)
print('checks if all the characters of a string are lowercase characters (a-z).')
print ('abcd123#'.islower())
print ('Abcd123#'.islower())
print("-"*50)
print('checks if all the characters of a string are uppercase characters (A-Z).')
print ('ABCD123#'.isupper())
print ('Abcd123#'.isupper())
print("-"*50)
print('')



